[pytest]
markers =
    login: test para el login
    agregar_carrito: test para agregar producto al carrito y verificarlo
    verificar_pagina: testes relacionados a la verificación de la página y ciertos elementos
    api: tests que usan API
    smoke: pruebas críticas y rápidas
    negativo: pruebas de casos negativos

addopts = -v --html=reports/report.html --self-contained-html
#Modo verbose: muestra cada test individualmente
#--html=reports/report.html   Genera el reporte HTML en esa ruta específica
#--self-contained-html     Incluye CSS, JS e imágenes en un solo archivo