[pytest]
markers =
    login: test para el login
    agregar_carrito: test para agregar producto al carrito y verificarlo
    verificar_pagina: testes relacionados a la verificación de la página y ciertos elementos